<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Version>0.3.4</Version><AssemblyName>BurebistaTipiWorkbench</AssemblyName>
    <NuGetAudit>false</NuGetAudit>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <GameDir Condition="'$(GameDir)' == ''">C:\Program Files (x86)\Steam\steamapps\common\TheLongDark</GameDir>
    <GameRefs>$(GameDir)\MelonLoader\Il2CppAssemblies</GameRefs>
    <LoaderRefs>$(GameDir)\MelonLoader\net6</LoaderRefs>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\WorkbenchAtlas.png" LogicalName="TipiWorkbench.Atlas.png" />
    <Reference Include="$(GameRefs)\UnityEngine.AudioModule.dll" Private="false" />
    
    <Reference Include="$(GameRefs)\UnityEngine.ImageConversionModule.dll" Private="false" />
    <Reference Include="$(LoaderRefs)\MelonLoader.dll" Private="false" />
    <Reference Include="$(LoaderRefs)\0Harmony.dll" Private="false" />
    <Reference Include="$(LoaderRefs)\Il2CppInterop.Runtime.dll" Private="false" />
    <Reference Include="$(GameRefs)\Assembly-CSharp.dll" Private="false" />
    <Reference Include="$(GameRefs)\Il2Cppmscorlib.dll" Private="false" />
    <Reference Include="$(GameRefs)\Il2CppTLD.IntBackedUnit.dll" Private="false" />
    <Reference Include="$(GameRefs)\Il2CppTLD.PDID.dll" Private="false" />
    <Reference Include="$(GameRefs)\UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="$(GameRefs)\UnityEngine.PhysicsModule.dll" Private="false" />
    <Reference Include="$(GameRefs)\UnityEngine.InputLegacyModule.dll" Private="false" />
    <Reference Include="$(GameRefs)\UnityEngine.IMGUIModule.dll" Private="false" />
    <Reference Include="$(GameRefs)\UnityEngine.TextRenderingModule.dll" Private="false" />
    <Reference Include="$(GameRefs)\Unity.Addressables.dll" Private="false" />
    <Reference Include="$(GameRefs)\Unity.ResourceManager.dll" Private="false" />
  </ItemGroup>
</Project>















